[package]
name = "paint-party-server"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = {version = "0.5.1", features = ["json"]}
serde = "1.0.207"
macroquad = "0.4.12"
serde_json = "1.0.125"
log = "0.4"
fern = "0.6.2"
chrono = "0.4.38"
